name: Run Command
description: Trigger a workflow dispatch on a pull request head ref
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  permissions:
    default: write,maintain,admin
    description: Permissions to require for the command
    required: false
  pull-request-url:
    default: ${{ github.event.issue.pull_request.html_url }}
    description: The Pull Request URL
    required: false
  reaction:
    default: rocket
    description: Reaction to add to the triggering comment
    required: false
runs:
  steps:
    - id: command
      uses: github/command@3442f3fa1efe01bdb024b157083c337902d17372 # v2
      with:
        allowed_contexts: pull_request
        command: .run
        github_token: ${{ inputs.github-token }}
        permissions: ${{ inputs.permissions }}
        reaction: ${{ inputs.reaction }}
        skip_ci: true
    - id: checkout
      if: steps.command.outputs.continue == 'true'
      uses: shikanime-studio/actions/checkout@5993d4d95befc190a14c0d143583683d203ad8d1 # v9
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - if: steps.command.outputs.continue == 'true'
      uses: shikanime-studio/actions/run@5993d4d95befc190a14c0d143583683d203ad8d1 # v9
      with:
        github-token: ${{ inputs.github-token }}
        ref: ${{ steps.checkout.outputs.head-ref }}
        workflow: ${{ steps.command.outputs.params }}
  using: composite
